Repository AngeloDotNet/GestioneSagre, pull requests merged in 2022-06, with the labels that each got.

#2 Creazione del progetto #1
  GestioneSagre.sln
Labels: enhancement

#4 Implementazione docker #3
  Dockerfile
  GestioneSagre.sln
  docker-compose.yml
Labels: enhancement

#8 Creazione progetto Blazor Wasm #7
  GestioneSagre.sln
  src/GestioneSagre.Web/Client/App.razor
  src/GestioneSagre.Web/Client/GestioneSagre.Web.Client.csproj
  src/GestioneSagre.Web/Client/Pages/Counter.razor
  src/GestioneSagre.Web/Client/Pages/FetchData.razor
  src/GestioneSagre.Web/Client/Pages/Index.razor
  src/GestioneSagre.Web/Client/Program.cs
  src/GestioneSagre.Web/Client/Properties/launchSettings.json
  src/GestioneSagre.Web/Client/Shared/MainLayout.razor
  src/GestioneSagre.Web/Client/Shared/MainLayout.razor.css
  src/GestioneSagre.Web/Client/Shared/NavMenu.razor
  src/GestioneSagre.Web/Client/Shared/NavMenu.razor.css
  src/GestioneSagre.Web/Client/Shared/SurveyPrompt.razor
  src/GestioneSagre.Web/Client/_Imports.razor
  src/GestioneSagre.Web/Client/wwwroot/css/app.css
  src/GestioneSagre.Web/Client/wwwroot/css/bootstrap/bootstrap.min.css
  src/GestioneSagre.Web/Client/wwwroot/css/bootstrap/bootstrap.min.css.map
  src/GestioneSagre.Web/Client/wwwroot/css/open-iconic/FONT-LICENSE
  src/GestioneSagre.Web/Client/wwwroot/css/open-iconic/ICON-LICENSE
  src/GestioneSagre.Web/Client/wwwroot/css/open-iconic/README.md
  src/GestioneSagre.Web/Client/wwwroot/css/open-iconic/font/css/open-iconic-bootstrap.min.css
  src/GestioneSagre.Web/Client/wwwroot/css/open-iconic/font/fonts/open-iconic.eot
  src/GestioneSagre.Web/Client/wwwroot/css/open-iconic/font/fonts/open-iconic.otf
  src/GestioneSagre.Web/Client/wwwroot/css/open-iconic/font/fonts/open-iconic.svg
  src/GestioneSagre.Web/Client/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf
  src/GestioneSagre.Web/Client/wwwroot/css/open-iconic/font/fonts/open-iconic.woff
  src/GestioneSagre.Web/Client/wwwroot/favicon.ico
  src/GestioneSagre.Web/Client/wwwroot/icon-512.png
  src/GestioneSagre.Web/Client/wwwroot/index.html
  src/GestioneSagre.Web/Client/wwwroot/manifest.json
  src/GestioneSagre.Web/Client/wwwroot/service-worker.js
  src/GestioneSagre.Web/Client/wwwroot/service-worker.published.js
  src/GestioneSagre.Web/Server/Controllers/WeatherForecastController.cs
  src/GestioneSagre.Web/Server/GestioneSagre.Web.Server.csproj
  src/GestioneSagre.Web/Server/Pages/Error.cshtml
  src/GestioneSagre.Web/Server/Pages/Error.cshtml.cs
  src/GestioneSagre.Web/Server/Program.cs
  src/GestioneSagre.Web/Server/Properties/launchSettings.json
  src/GestioneSagre.Web/Server/Startup.cs
  src/GestioneSagre.Web/Server/appsettings.Development.json
  src/GestioneSagre.Web/Server/appsettings.json
  src/GestioneSagre.Web/Shared/GestioneSagre.Web.Shared.csproj
  src/GestioneSagre.Web/Shared/WeatherForecast.cs
Labels: enhancement

#10 Configurazione file .editorconfig #9
  .editorconfig
  GestioneSagre.sln
Labels: enhancement

#12 Configurazione workflow Linter #11
  .github/workflows/linter.yml
  GestioneSagre.sln
Labels: enhancement

#15 Aggiornamento file README #14
  README.md
Labels: enhancement

#16 Sync Master --> Implementazione WebApi Gestione #13
  README.md
Labels: fix

#20 19 missing push commit
  src/GestioneSagre.Web.Server/Startup.cs
Labels: fix

#21 Configurazione workflow Publish #18
  .github/workflows/publish.yml
  GestioneSagre.sln
  src/GestioneSagre.Web.Server/GestioneSagre.Web.Server.csproj
  src/GestioneSagre.Web.Server/version.json
Labels: enhancement

#23 Implementazione WebApi Gestione logo #22
  src/GestioneSagre.Business/GlobalUsings.cs
  src/GestioneSagre.Business/Services/Application/Logo/EfCoreLogoService.cs
  src/GestioneSagre.Business/Services/Application/Logo/ILogoService.cs
  src/GestioneSagre.DataAccess/GestioneSagre.DataAccess.csproj
  src/GestioneSagre.DataAccess/GlobalUsings.cs
  src/GestioneSagre.DataAccess/Models/Services/Infrastructure/IImagePersister.cs
  src/GestioneSagre.DataAccess/Models/Services/Infrastructure/InsecureImagePersister.cs
  src/GestioneSagre.DataAccess/Models/Services/Infrastructure/MagickNetImagePersister.cs
  src/GestioneSagre.Models/GestioneSagre.Models.csproj
  src/GestioneSagre.Models/GlobalUsings.cs
  src/GestioneSagre.Models/InputModels/Logo/LogoEditInputModel.cs
  src/GestioneSagre.Web.Server/Controllers/LogoController.cs
  src/GestioneSagre.Web.Server/GlobalUsings.cs
  src/GestioneSagre.Web.Server/Startup.cs
Labels: enhancement

#26 Aggiunta Bootstrap e FontAwesome #25
  src/GestioneSagre.Web.Client/Pages/Index.razor
  src/GestioneSagre.Web.Client/Shared/NavMenu.razor
  src/GestioneSagre.Web.Client/libman.json
  src/GestioneSagre.Web.Client/wwwroot/css/app.css
  src/GestioneSagre.Web.Client/wwwroot/css/bootstrap/bootstrap.min.css
  src/GestioneSagre.Web.Client/wwwroot/css/bootstrap/bootstrap.min.css.map
  src/GestioneSagre.Web.Client/wwwroot/css/open-iconic/FONT-LICENSE
  src/GestioneSagre.Web.Client/wwwroot/css/open-iconic/ICON-LICENSE
  src/GestioneSagre.Web.Client/wwwroot/css/open-iconic/README.md
  src/GestioneSagre.Web.Client/wwwroot/css/open-iconic/font/css/open-iconic-bootstrap.min.css
  src/GestioneSagre.Web.Client/wwwroot/css/open-iconic/font/fonts/open-iconic.eot
  src/GestioneSagre.Web.Client/wwwroot/css/open-iconic/font/fonts/open-iconic.otf
  src/GestioneSagre.Web.Client/wwwroot/css/open-iconic/font/fonts/open-iconic.svg
  src/GestioneSagre.Web.Client/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf
  src/GestioneSagre.Web.Client/wwwroot/css/open-iconic/font/fonts/open-iconic.woff
  src/GestioneSagre.Web.Client/wwwroot/index.html
  src/GestioneSagre.Web.Client/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css
  src/GestioneSagre.Web.Client/wwwroot/lib/bootstrap/dist/js/bootstrap.min.js
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/css/all.min.css
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-brands-400.eot
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-brands-400.svg
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-brands-400.ttf
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-brands-400.woff
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-brands-400.woff2
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-regular-400.eot
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-regular-400.svg
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-regular-400.ttf
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-regular-400.woff
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-regular-400.woff2
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-solid-900.eot
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-solid-900.svg
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-solid-900.ttf
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-solid-900.woff
  src/GestioneSagre.Web.Client/wwwroot/lib/font-awesome/webfonts/fa-solid-900.woff2
  src/GestioneSagre.Web.Client/wwwroot/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js
  src/GestioneSagre.Web.Client/wwwroot/lib/jquery-validation/dist/additional-methods.min.js
  src/GestioneSagre.Web.Client/wwwroot/lib/jquery-validation/dist/jquery.validate.min.js
  src/GestioneSagre.Web.Client/wwwroot/lib/jquery-validation/dist/localization/messages_it.min.js
  src/GestioneSagre.Web.Client/wwwroot/lib/jquery/dist/jquery.min.js
  src/GestioneSagre.Web.Client/wwwroot/lib/jquery/dist/jquery.slim.min.js
  src/GestioneSagre.Web.Client/wwwroot/lib/popper/dist/umd/popper.min.js
Labels: enhancement

#27 Aggiunta documentazione file README #24
  README.md
Labels: enhancement

#31 Rimuovere job Push da workflow Linter #30
  .github/workflows/linter.yml
Labels: fix

#35 34 scrutor
  src/GestioneSagre.Business/Extensions/ConfigureServices.cs
  src/GestioneSagre.Business/GestioneSagre.Business.csproj
  src/GestioneSagre.Business/GlobalUsings.cs
  src/GestioneSagre.Models/GestioneSagre.Models.csproj
  src/GestioneSagre.Web.Server/GestioneSagre.Web.Server.csproj
  src/GestioneSagre.Web.Server/GlobalUsings.cs
  src/GestioneSagre.Web.Server/Startup.cs
Labels: enhancement

#44 Refactoring del codice #43
  src/GestioneSagre.Business/Extensions/ApplicationServices.cs
  src/GestioneSagre.Business/Extensions/SwaggerServices.cs
  src/GestioneSagre.Business/GestioneSagre.Business.csproj
  src/GestioneSagre.Business/GlobalUsings.cs
  src/GestioneSagre.Web.Server/GlobalUsings.cs
  src/GestioneSagre.Web.Server/Startup.cs
Labels: refactoring

#46 Fix #45
  README.md
  src/GestioneSagre.Web.Client.UI/GestioneSagre.Web.Client.UI.csproj
Labels: fix

#48 Configurazione parte Client per PWA ma senza l'offline #47
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  src/GestioneSagre.Web.Client.UI/Pages/Index.razor
  src/GestioneSagre.Web.Client/wwwroot/favicon.ico
  src/GestioneSagre.Web.Client/wwwroot/icon-128.png
  src/GestioneSagre.Web.Client/wwwroot/icon-256.png
  src/GestioneSagre.Web.Client/wwwroot/icon-512.png
  src/GestioneSagre.Web.Client/wwwroot/index.html
  src/GestioneSagre.Web.Client/wwwroot/manifest.json
  src/GestioneSagre.Web.Client/wwwroot/service-worker.js
  src/GestioneSagre.Web.Client/wwwroot/service-worker.published.js
  src/GestioneSagre.Web.Client/wwwroot/sw-registrator.js
Labels: new implementation

#49 39 documentazione webapi gestione logo
  src/GestioneSagre.Business/Extensions/SwaggerServices.cs
  src/GestioneSagre.Business/GestioneSagre.Business.csproj
  src/GestioneSagre.Business/GlobalUsings.cs
  src/GestioneSagre.Web.Server/Controllers/LogoController.cs
Labels: new implementation

#55 54 caricamento assembly client tramite lazy loading
  GestioneSagre.sln
  src/GestioneSagre.Web.Client.UI/App.razor
  src/GestioneSagre.Web.Client.UI/GestioneSagre.Web.Client.UI.csproj
  src/GestioneSagre.Web.Client.UI/Pages/Index.razor
  src/GestioneSagre.Web.Client.UI/Pages/Welcome.razor
  src/GestioneSagre.Web.Client.UI/_Imports.razor
  src/GestioneSagre.Web.Client/App.razor
  src/GestioneSagre.Web.Client/App.razor.cs
  src/GestioneSagre.Web.Client/GestioneSagre.Web.Client.csproj
  src/GestioneSagre.Web.Client/GlobalUsings.cs
  src/GestioneSagre.Web.Client/Pages/Index.razor
  src/GestioneSagre.Web.Client/Program.cs
  src/GestioneSagre.Web.Client/Shared/MainLayout.razor
  src/GestioneSagre.Web.Client/Shared/MainLayout.razor.css
  src/GestioneSagre.Web.Client/Shared/NavMenu.razor
  src/GestioneSagre.Web.Client/Shared/NavMenu.razor.css
  src/GestioneSagre.Web.Client/_Imports.razor
Labels: refactoring

#78 Aggiornamento pacchetti NuGet #77
  src/GestioneSagre.DataAccess/GestioneSagre.DataAccess.csproj
  src/GestioneSagre.Web.Client/GestioneSagre.Web.Client.csproj
Labels: new implementation

#81 Documentazione WebApi Gestione Versione #79
  src/GestioneSagre.Web.Server/Controllers/VersioneController.cs
Labels: documentation

#82 Documentazione WebApi Gestione Config. Iniziale (Festa) #38
  src/GestioneSagre.Web.Server/Controllers/FestaController.cs
Labels: documentation

#83 33 informazioni sul prodotto
  src/GestioneSagre.Web.Client.UI/Pages/Help/Informazioni.razor
  src/GestioneSagre.Web.Client.UI/Pages/Help/Informazioni.razor.css
  src/GestioneSagre.Web.Client.UI/Pages/Welcome.razor
  src/GestioneSagre.Web.Client.UI/Pages/Welcome.razor.css
  src/GestioneSagre.Web.Client/GestioneSagre.Web.Client.csproj
  src/GestioneSagre.Web.Client/Shared/NavMenu.razor
  src/GestioneSagre.Web.Client/wwwroot/images/hero.jpg
Labels: new implementation

#84 SQL Server - Gestione errori transienti #41
  src/GestioneSagre.Web.Server/Startup.cs
  src/GestioneSagre.Web.Server/appsettings.json
Labels: new implementation

#86 42 sql server politica di fallback
  src/GestioneSagre.Business/Extensions/ConfigureServices.cs
  src/GestioneSagre.Business/GlobalUsings.cs
  src/GestioneSagre.Business/Services/Application/Logo/EfCoreLogoService.cs
  src/GestioneSagre.DataAccess/GestioneSagre.DataAccess.csproj
  src/GestioneSagre.DataAccess/GlobalUsings.cs
  src/GestioneSagre.DataAccess/Models/Services/Infrastructure/LocalTransactionLogger.cs
  src/GestioneSagre.DataAccess/Models/Services/Infrastructure/MagickNetImagePersister.cs
  src/GestioneSagre.DataAccess/Models/Services/Interfaces/IImagePersister.cs
  src/GestioneSagre.DataAccess/Models/Services/Interfaces/ITransactionLogger.cs
  src/GestioneSagre.DataAccess/Models/Services/Interfaces/InsecureImagePersister.cs
Labels: new implementation

#118 Refactoring Extension Method ConfigureServices #117
  src/GestioneSagre.Business/Extensions/ConfigureServices.cs
  src/GestioneSagre.Web.PrivateAPI/Startup.cs
  src/GestioneSagre.Web.Server/Startup.cs
Labels: refactoring

#119 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: question
